### ISSUE TITLE
LINT(GET-STARTED): Actualize for public usage

### ISSUE THREAD

**Issue by azinit** [feature-sliced/eslint-config#37]
## Problem

Package should have all required for usage at real projects
- [x] Docs
- [x] JS/TS Support
- [ ] Possibility to customize config (basely)

## Steps
- [x] #24 
- [x] #22 
- [x] #38
- [x] #21 
- [x] LINT: Check messages
- [x] Check by "share config" article
   https://eslint.org/docs/developer-guide/shareable-configs#creating-a-shareable-config
